# Generated by Django 5.0.4 on 2024-05-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='Accounts',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
